/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouRouteImport } from './routes/you'
import { Route as WarmupRouteImport } from './routes/warmup'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as StopwatchRouteImport } from './routes/stopwatch'
import { Route as StaTrainerRouteImport } from './routes/sta-trainer'
import { Route as StaTablesRouteImport } from './routes/sta-tables'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PerformancesRouteImport } from './routes/performances'
import { Route as LogRouteImport } from './routes/log'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as DiveIdRouteImport } from './routes/dive.$id'
import { Route as DisciplineCodeRouteImport } from './routes/discipline.$code'
import { Route as CoachAthleteIdRouteImport } from './routes/coach.athlete.$id'

const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const WarmupRoute = WarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const StopwatchRoute = StopwatchRouteImport.update({
  id: '/stopwatch',
  path: '/stopwatch',
  getParentRoute: () => rootRouteImport,
} as any)
const StaTrainerRoute = StaTrainerRouteImport.update({
  id: '/sta-trainer',
  path: '/sta-trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const StaTablesRoute = StaTablesRouteImport.update({
  id: '/sta-tables',
  path: '/sta-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformancesRoute = PerformancesRouteImport.update({
  id: '/performances',
  path: '/performances',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const DiveIdRoute = DiveIdRouteImport.update({
  id: '/dive/$id',
  path: '/dive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineCodeRoute = DisciplineCodeRouteImport.update({
  id: '/discipline/$code',
  path: '/discipline/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachAthleteIdRoute = CoachAthleteIdRouteImport.update({
  id: '/athlete/$id',
  path: '/athlete/$id',
  getParentRoute: () => CoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/history': typeof HistoryRoute
  '/log': typeof LogRoute
  '/performances': typeof PerformancesRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sta-tables': typeof StaTablesRoute
  '/sta-trainer': typeof StaTrainerRoute
  '/stopwatch': typeof StopwatchRoute
  '/tips': typeof TipsRoute
  '/train': typeof TrainRoute
  '/warmup': typeof WarmupRoute
  '/you': typeof YouRoute
  '/discipline/$code': typeof DisciplineCodeRoute
  '/dive/$id': typeof DiveIdRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/athlete/$id': typeof CoachAthleteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/history': typeof HistoryRoute
  '/log': typeof LogRoute
  '/performances': typeof PerformancesRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sta-tables': typeof StaTablesRoute
  '/sta-trainer': typeof StaTrainerRoute
  '/stopwatch': typeof StopwatchRoute
  '/tips': typeof TipsRoute
  '/train': typeof TrainRoute
  '/warmup': typeof WarmupRoute
  '/you': typeof YouRoute
  '/discipline/$code': typeof DisciplineCodeRoute
  '/dive/$id': typeof DiveIdRoute
  '/coach': typeof CoachIndexRoute
  '/coach/athlete/$id': typeof CoachAthleteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/history': typeof HistoryRoute
  '/log': typeof LogRoute
  '/performances': typeof PerformancesRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sta-tables': typeof StaTablesRoute
  '/sta-trainer': typeof StaTrainerRoute
  '/stopwatch': typeof StopwatchRoute
  '/tips': typeof TipsRoute
  '/train': typeof TrainRoute
  '/warmup': typeof WarmupRoute
  '/you': typeof YouRoute
  '/discipline/$code': typeof DisciplineCodeRoute
  '/dive/$id': typeof DiveIdRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/athlete/$id': typeof CoachAthleteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/coach'
    | '/dashboard'
    | '/equipment'
    | '/history'
    | '/log'
    | '/performances'
    | '/planner'
    | '/profile'
    | '/rankings'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/sta-tables'
    | '/sta-trainer'
    | '/stopwatch'
    | '/tips'
    | '/train'
    | '/warmup'
    | '/you'
    | '/discipline/$code'
    | '/dive/$id'
    | '/coach/'
    | '/coach/athlete/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/equipment'
    | '/history'
    | '/log'
    | '/performances'
    | '/planner'
    | '/profile'
    | '/rankings'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/sta-tables'
    | '/sta-trainer'
    | '/stopwatch'
    | '/tips'
    | '/train'
    | '/warmup'
    | '/you'
    | '/discipline/$code'
    | '/dive/$id'
    | '/coach'
    | '/coach/athlete/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/coach'
    | '/dashboard'
    | '/equipment'
    | '/history'
    | '/log'
    | '/performances'
    | '/planner'
    | '/profile'
    | '/rankings'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/sta-tables'
    | '/sta-trainer'
    | '/stopwatch'
    | '/tips'
    | '/train'
    | '/warmup'
    | '/you'
    | '/discipline/$code'
    | '/dive/$id'
    | '/coach/'
    | '/coach/athlete/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  CoachRoute: typeof CoachRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EquipmentRoute: typeof EquipmentRoute
  HistoryRoute: typeof HistoryRoute
  LogRoute: typeof LogRoute
  PerformancesRoute: typeof PerformancesRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  RankingsRoute: typeof RankingsRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaTablesRoute: typeof StaTablesRoute
  StaTrainerRoute: typeof StaTrainerRoute
  StopwatchRoute: typeof StopwatchRoute
  TipsRoute: typeof TipsRoute
  TrainRoute: typeof TrainRoute
  WarmupRoute: typeof WarmupRoute
  YouRoute: typeof YouRoute
  DisciplineCodeRoute: typeof DisciplineCodeRoute
  DiveIdRoute: typeof DiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warmup': {
      id: '/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof WarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stopwatch': {
      id: '/stopwatch'
      path: '/stopwatch'
      fullPath: '/stopwatch'
      preLoaderRoute: typeof StopwatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sta-trainer': {
      id: '/sta-trainer'
      path: '/sta-trainer'
      fullPath: '/sta-trainer'
      preLoaderRoute: typeof StaTrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sta-tables': {
      id: '/sta-tables'
      path: '/sta-tables'
      fullPath: '/sta-tables'
      preLoaderRoute: typeof StaTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performances': {
      id: '/performances'
      path: '/performances'
      fullPath: '/performances'
      preLoaderRoute: typeof PerformancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/dive/$id': {
      id: '/dive/$id'
      path: '/dive/$id'
      fullPath: '/dive/$id'
      preLoaderRoute: typeof DiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline/$code': {
      id: '/discipline/$code'
      path: '/discipline/$code'
      fullPath: '/discipline/$code'
      preLoaderRoute: typeof DisciplineCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/athlete/$id': {
      id: '/coach/athlete/$id'
      path: '/athlete/$id'
      fullPath: '/coach/athlete/$id'
      preLoaderRoute: typeof CoachAthleteIdRouteImport
      parentRoute: typeof CoachRoute
    }
  }
}

interface CoachRouteChildren {
  CoachIndexRoute: typeof CoachIndexRoute
  CoachAthleteIdRoute: typeof CoachAthleteIdRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachIndexRoute: CoachIndexRoute,
  CoachAthleteIdRoute: CoachAthleteIdRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  CoachRoute: CoachRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EquipmentRoute: EquipmentRoute,
  HistoryRoute: HistoryRoute,
  LogRoute: LogRoute,
  PerformancesRoute: PerformancesRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  RankingsRoute: RankingsRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaTablesRoute: StaTablesRoute,
  StaTrainerRoute: StaTrainerRoute,
  StopwatchRoute: StopwatchRoute,
  TipsRoute: TipsRoute,
  TrainRoute: TrainRoute,
  WarmupRoute: WarmupRoute,
  YouRoute: YouRoute,
  DisciplineCodeRoute: DisciplineCodeRoute,
  DiveIdRoute: DiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
