/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as LogRouteImport } from './routes/log'
import { Route as StaTrainerRouteImport } from './routes/sta-trainer'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisciplineCodeRouteImport } from './routes/discipline.$code'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const StaTrainerRoute = StaTrainerRouteImport.update({
  id: '/sta-trainer',
  path: '/sta-trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineCodeRoute = DisciplineCodeRouteImport.update({
  id: '/discipline/$code',
  path: '/discipline/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/history': typeof HistoryRoute
  '/log': typeof LogRoute
  '/planner': typeof PlannerRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sta-trainer': typeof StaTrainerRoute
  '/discipline/$code': typeof DisciplineCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/history': typeof HistoryRoute
  '/log': typeof LogRoute
  '/planner': typeof PlannerRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sta-trainer': typeof StaTrainerRoute
  '/discipline/$code': typeof DisciplineCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/equipment': typeof EquipmentRoute
  '/history': typeof HistoryRoute
  '/log': typeof LogRoute
  '/planner': typeof PlannerRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sta-trainer': typeof StaTrainerRoute
  '/discipline/$code': typeof DisciplineCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/equipment'
    | '/history'
    | '/log'
    | '/planner'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/sta-trainer'
    | '/discipline/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/equipment'
    | '/history'
    | '/log'
    | '/planner'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/sta-trainer'
    | '/discipline/$code'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/equipment'
    | '/history'
    | '/log'
    | '/planner'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/sta-trainer'
    | '/discipline/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  EquipmentRoute: typeof EquipmentRoute
  HistoryRoute: typeof HistoryRoute
  LogRoute: typeof LogRoute
  PlannerRoute: typeof PlannerRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaTrainerRoute: typeof StaTrainerRoute
  DisciplineCodeRoute: typeof DisciplineCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sta-trainer': {
      id: '/sta-trainer'
      path: '/sta-trainer'
      fullPath: '/sta-trainer'
      preLoaderRoute: typeof StaTrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline/$code': {
      id: '/discipline/$code'
      path: '/discipline/$code'
      fullPath: '/discipline/$code'
      preLoaderRoute: typeof DisciplineCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  EquipmentRoute: EquipmentRoute,
  HistoryRoute: HistoryRoute,
  LogRoute: LogRoute,
  PlannerRoute: PlannerRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaTrainerRoute: StaTrainerRoute,
  DisciplineCodeRoute: DisciplineCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
